/**
 * The audible voice check at the end of calibration: generated by the worker
 * as its warm-up line, spoken aloud before the setup overlay closes (only
 * when the user just enabled voice — silent on app boot), and rendered as a
 * dialogue block in the overlay while it plays.
 */
export const VOICE_CHECK_SPEAKER = 'Mission Control';
export const VOICE_CHECK_LINE =
  'Voice systems calibrated and online. All mentors are on comms — see you in the briefing room.';
